[gov_officials]
delegate = 'Erinor'
local_council = ['Volaworand', 'Aumeltopia', 'Auphelia']
crs = ['Sandaoguo', 'Farengeto', 'Kringalia', 'Erinor', 'Tsunamy', 'Pencil Sharpeners 2']
legcomm = ['United States of Vietnam', 'Nakarisaune', 'Erinor']
general_corps = ['United States of Vietnam', 'Roavin', 'Nakarisaune']
mora_advisory_council = ['Kringalia', 'Volaworand', 'Islands of Unity', 'Aidenfieeld', 'Beepee', 'Roavin', 'Pencil Sharpeners 2']
cabinet_advisors = ['Amerion', 'Roavin', 'Islands of Unity', 'Heliseum']
coa = 'Amerion'
pm = 'Nakarisaune'
mora = 'Rebel-topia'
mofa = 'Sandaoguo'
moma = 'Witchcraft and Sorcery'
hc_chief_justice = 'Kringalia'
hc_justices = ['Kringalia', 'Belschaft', 'Rebeltopia', 'Awesomiasa']
election_commissioner = 'Tsunamy'

[test]
region_nation_num = 6000

[misc]
secret_ballot_forum_acc = 'The Vote Collector'
news_outlet_adder = 'Amerion'