[gov_officials]
delegate = 'Erinor'
local_council = ['Volaworand', 'Aumeltopia', 'Auphelia']
crs = ['Sandaoguo', 'Farengeto', 'Kringalia', 'Erinor', 'Tsunamy', 'Pencil Sharpeners 2']
legcomm = ['United States of Vietnam', 'Nakarisaune', 'Erinor']
general_corps = ['United States of Vietnam', 'Roavin', 'Nakarisaune']
mora_advisory_council = ['Kringalia', 'Volaworand', 'Islands of Unity', 'Aidenfieeld', 'Beepee', 'Roavin', 'Pencil Sharpeners 2']
cabinet_advisors = ['Amerion', 'Roavin', 'Islands of Unity', 'Heliseum']
coa = 'Bzerneleg'
pm = 'Nakarisaune'
mora = 'Rebel-topia'
mofa = 'Sandaoguo'
moma = 'Witchcraft and Sorcery'
hc_chief_justice = 'Kringalia'
hc_justices = ['Kringalia', 'Belschaft', 'Rebeltopia', 'Awesomiasa']
election_commissioner = 'Tsunamy'

[test]
region_nation_num = 6000

[misc]
secret_ballot_forum_acc = 'The Vote Collector'
news_outlet_adder = 'Amerion'

[active_news_outlets]
Coco = 'https://www.nationstates.net/page=dispatches/nation=lama_glama_publishing_group'

[other_news_outlets]
TestNews = 'https://www.nationstates.net/region=the_south_pacific'

[proscriptions]
[proscriptions.'Funkadelia']
type = 'Individual'
start_date = '25-07-2018'
association = '[region]Lone Wolves United[/region]'
note = '[url=https://tspforums.xyz/thread-6362.html]Cabinet statement[/url]'

[proscriptions.'Lamb Stone']
type = 'Individual'
start_date = '25-07-2018'
association = '[region]Lone Wolves United[/region]'
note = '[url=https://tspforums.xyz/thread-6362.html]Cabinet statement[/url]'

[proscriptions.'Evil Wolf']
type = 'Individual'
start_date = '25-07-2018'
association = '[region]Lone Wolves United[/region]'
note = '[url=https://tspforums.xyz/thread-6362.html]Cabinet statement[/url]'

[proscriptions.'McMannia']
type = 'Individual'
start_date = '25-07-2018'
association = '[region]HYDRA Command[/region], [region]The Ragerian Imperium[/region]'
note = '[url=https://tspforums.xyz/thread-6362.html]Cabinet statement[/url]'

[proscriptions.'HYDRA Command']
type = 'Organization'
start_date = '25-07-2018'
association = 'N/A'
note = '[url=https://tspforums.xyz/thread-6362.html]Cabinet statement[/url]'


[urls]
f_bantam_harbour = 'https://tspforums.xyz/forum-109.html'
f_bantam_harbour_map = 'https://tspforums.xyz/thread-241.html'
f_knowhere = 'https://tspforums.xyz/forum-292.html'
f_spam = 'https://tspforums.xyz/forum-14.html'
f_news = 'https://tspforums.xyz/forum-22.html'
f_crs = 'https://tspforums.xyz/forum-53.html'
f_cabinet_twitter = 'https://tspforums.xyz/thread-6621.html'
f_executive_offices = 'https://tspforums.xyz/forum-32.html'
f_assembly_archive = 'https://tspforums.xyz/forum-91.html'
roleplay_guide = 'https://www.nationstates.net/page=dispatch/id=920399'
f_wa = 'https://tspforums.xyz/forum-35.html'
forum = 'https://tspforums.xyz/index.php'
rmb = 'https://www.nationstates.net/page=display_region_rmb/region=the_south_pacific'
discord = 'https://discordapp.com/invite/tEyyDyh'
ns_faq = 'https://www.nationstates.net/page=faq'
ns_wa = 'https://www.nationstates.net/page=un'
ns_telegram = 'https://www.nationstates.net/page=telegrams'
ns_nation_census = 'https://www.nationstates.net/page=list_nations/mode=g?censusid=0'
ns_pol_faq = 'https://www.nationstates.net/page=faq#politics'
ns_codes = 'https://www.nationstates.net/page=dispatch/id=330837'
ns_issue_types = 'https://www.nationstates.net/page=dispatch/id=299923'
ns_tools = 'https://www.nationstates.net/page=dispatch/id=219095'
nsf_got_issues = 'https://forum.nationstates.net/viewforum.php?f=13&sid=0723b6b72ddc34d1d0986556306443cd'
secret_ballot_forum_acc = 'https://tspforums.xyz/user-73.html'
lc_intro = 'https://www.nationstates.net/page=dispatch/id=1199328'
rmb_rules = 'https://www.nationstates.net/page=dispatch/id=1199335'
lc_policies = 'https://www.nationstates.net/page=dispatch/id=1199330'
lc_elections = 'https://www.nationstates.net/page=dispatch/id=1186281'
f_assembly_office = 'https://tspforums.xyz/thread-5131.html'
court_orcs = 'https://tspforums.xyz/forum-393.html'
f_legislator_signup = 'https://tspforums.xyz/forum-11.html'
f_assembly_hall = 'https://tspforums.xyz/forum-27.html'
f_private_assembly_hall = 'https://tspforums.xyz/forum-28.html'
f_voting_chamber = 'https://tspforums.xyz/forum-29.html'
f_legislator_signup_faq = 'https://tspforums.xyz/thread-5837-post-188674.html#pid188674'
f_legislator_loa = 'https://tspforums.xyz/thread-5838.html'